from django.urls import path
from rest_framework.routers import DefaultRouter

from .views import (
	ExamGradeScaleViewSet,
	ExamAttendanceCreateSearchAPIView,
	ExamAttendanceIndexAPIView,
	ExamAttendanceReportSearchAPIView,
	ExamAttendanceStoreAPIView,
	ExamPlanAdmitCardGenerateAPIView,
	ExamPlanAdmitCardIndexAPIView,
	ExamPlanAdmitCardSearchAPIView,
	ExamPlanAdmitCardSettingAPIView,
	ExamPlanSeatPlanGenerateAPIView,
	ExamPlanSeatPlanIndexAPIView,
	ExamPlanSeatPlanSearchAPIView,
	ExamPlanSeatPlanSettingAPIView,
	ExamMarkViewSet,
	ExamMarksRegisterCreateSearchAPIView,
	ExamMarksRegisterIndexAPIView,
	ExamMarksRegisterReportSearchAPIView,
	ExamMarksRegisterStoreAPIView,
	ExamMeritSearchAPIView,
	ExamMeritPrintAPIView,
	ExamReportIndexAPIView,
	ExamReportStudentPrintAPIView,
	ExamReportStudentSearchAPIView,
	ExamResultPublishIndexAPIView,
	ExamResultPublishSearchAPIView,
	ExamResultPublishStoreAPIView,
	ExamScheduleIndexAPIView,
	ExamSchedulePrintAPIView,
	ExamScheduleReportSearchAPIView,
	ExamScheduleSearchAPIView,
	ExamScheduleStoreAPIView,
	ExamSetupIndexAPIView,
	ExamSetupSearchAPIView,
	ExamSetupStoreAPIView,
	ExamSetupSubjectByClassAPIView,
	ExamScheduleViewSet,
	ExamTypeDeleteAPIView,
	ExamTypeEditAPIView,
	ExamTypeIndexAPIView,
	ExamTypeStoreAPIView,
	ExamTypeUpdateAPIView,
	ExamTypeViewSet,
	ExamViewSet,
	OnlineExamDeleteAPIView,
	OnlineExamIndexAPIView,
	OnlineExamMarksRegisterAPIView,
	OnlineExamPublishAPIView,
	OnlineExamPublishCancelAPIView,
	OnlineExamResultAPIView,
	OnlineExamStoreAPIView,
	OnlineExamUpdateAPIView,
)

router = DefaultRouter()
router.register("types", ExamTypeViewSet, basename="exam-type")
router.register("grade-scales", ExamGradeScaleViewSet, basename="exam-grade-scale")
router.register("exams", ExamViewSet, basename="exam")
router.register("schedules", ExamScheduleViewSet, basename="exam-schedule")
router.register("marks", ExamMarkViewSet, basename="exam-mark")

urlpatterns = [
	path("exam-type/", ExamTypeIndexAPIView.as_view(), name="exam-type-index"),
	path("exam-type/edit/<int:exam_type_id>/", ExamTypeEditAPIView.as_view(), name="exam-type-edit"),
	path("exam-type/store/", ExamTypeStoreAPIView.as_view(), name="exam-type-store"),
	path("exam-type/update/", ExamTypeUpdateAPIView.as_view(), name="exam-type-update"),
	path("exam-type/delete/<int:exam_type_id>/", ExamTypeDeleteAPIView.as_view(), name="exam-type-delete"),
	path("exam-setup/index/", ExamSetupIndexAPIView.as_view(), name="exam-setup-index"),
	path("exam-setup/search/", ExamSetupSearchAPIView.as_view(), name="exam-setup-search"),
	path("exam-setup/store/", ExamSetupStoreAPIView.as_view(), name="exam-setup-store"),
	path("exam-setup/subjects/", ExamSetupSubjectByClassAPIView.as_view(), name="exam-setup-subjects"),
	path("exam-schedule/index/", ExamScheduleIndexAPIView.as_view(), name="exam-schedule-index"),
	path("exam-schedule/search/", ExamScheduleSearchAPIView.as_view(), name="exam-schedule-search"),
	path("exam-schedule/store/", ExamScheduleStoreAPIView.as_view(), name="exam-schedule-store"),
	path("exam-schedule/report-search/", ExamScheduleReportSearchAPIView.as_view(), name="exam-schedule-report-search"),
	path("exam-schedule/print/", ExamSchedulePrintAPIView.as_view(), name="exam-schedule-print"),
	path("exam-attendance/index/", ExamAttendanceIndexAPIView.as_view(), name="exam-attendance-index"),
	path("exam-attendance/create-search/", ExamAttendanceCreateSearchAPIView.as_view(), name="exam-attendance-create-search"),
	path("exam-attendance/store/", ExamAttendanceStoreAPIView.as_view(), name="exam-attendance-store"),
	path("exam-attendance/report-search/", ExamAttendanceReportSearchAPIView.as_view(), name="exam-attendance-report-search"),
	path("exam-marks/index/", ExamMarksRegisterIndexAPIView.as_view(), name="exam-marks-index"),
	path("exam-marks/create-search/", ExamMarksRegisterCreateSearchAPIView.as_view(), name="exam-marks-create-search"),
	path("exam-marks/store/", ExamMarksRegisterStoreAPIView.as_view(), name="exam-marks-store"),
	path("exam-marks/report-search/", ExamMarksRegisterReportSearchAPIView.as_view(), name="exam-marks-report-search"),
	path("exam-result-publish/index/", ExamResultPublishIndexAPIView.as_view(), name="exam-result-publish-index"),
	path("exam-result-publish/search/", ExamResultPublishSearchAPIView.as_view(), name="exam-result-publish-search"),
	path("exam-result-publish/store/", ExamResultPublishStoreAPIView.as_view(), name="exam-result-publish-store"),
	path("exam-report/index/", ExamReportIndexAPIView.as_view(), name="exam-report-index"),
	path("exam-report/student-search/", ExamReportStudentSearchAPIView.as_view(), name="exam-report-student-search"),
	path("exam-report/student-print/", ExamReportStudentPrintAPIView.as_view(), name="exam-report-student-print"),
	path("exam-report/merit-search/", ExamMeritSearchAPIView.as_view(), name="exam-report-merit-search"),
	path("exam-report/merit-print/", ExamMeritPrintAPIView.as_view(), name="exam-report-merit-print"),
	# Online Exam
	path("online-exam/", OnlineExamIndexAPIView.as_view(), name="online-exam-index"),
	path("online-exam/store/", OnlineExamStoreAPIView.as_view(), name="online-exam-store"),
	path("online-exam/update/", OnlineExamUpdateAPIView.as_view(), name="online-exam-update"),
	path("online-exam/delete/", OnlineExamDeleteAPIView.as_view(), name="online-exam-delete"),
	path("online-exam/publish/<int:online_exam_id>/", OnlineExamPublishAPIView.as_view(), name="online-exam-publish"),
	path("online-exam/publish-cancel/<int:online_exam_id>/", OnlineExamPublishCancelAPIView.as_view(), name="online-exam-publish-cancel"),
	path("online-exam/marks-register/<int:online_exam_id>/", OnlineExamMarksRegisterAPIView.as_view(), name="online-exam-marks-register"),
	path("online-exam/result/<int:online_exam_id>/", OnlineExamResultAPIView.as_view(), name="online-exam-result"),
	# Exam Plan
	path("exam-plan/admit-card/setting/", ExamPlanAdmitCardSettingAPIView.as_view(), name="exam-plan-admit-card-setting"),
	path("exam-plan/admit-card/", ExamPlanAdmitCardIndexAPIView.as_view(), name="exam-plan-admit-card-index"),
	path("exam-plan/admit-card/search/", ExamPlanAdmitCardSearchAPIView.as_view(), name="exam-plan-admit-card-search"),
	path("exam-plan/admit-card/generate/", ExamPlanAdmitCardGenerateAPIView.as_view(), name="exam-plan-admit-card-generate"),
	path("exam-plan/seat-plan/setting/", ExamPlanSeatPlanSettingAPIView.as_view(), name="exam-plan-seat-plan-setting"),
	path("exam-plan/seat-plan/", ExamPlanSeatPlanIndexAPIView.as_view(), name="exam-plan-seat-plan-index"),
	path("exam-plan/seat-plan/search/", ExamPlanSeatPlanSearchAPIView.as_view(), name="exam-plan-seat-plan-search"),
	path("exam-plan/seat-plan/generate/", ExamPlanSeatPlanGenerateAPIView.as_view(), name="exam-plan-seat-plan-generate"),
]
urlpatterns += router.urls