# Generated by Django 4.2.11 on 2026-03-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentattendance",
            name="attendance_type",
            field=models.CharField(
                choices=[
                    ("P", "Present"),
                    ("A", "Absent"),
                    ("L", "Late"),
                    ("F", "Half Day"),
                    ("H", "Holiday"),
                ],
                max_length=1,
            ),
        ),
    ]
