# Generated by Django 4.2.11 on 2026-03-21 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_studentpromotionhistory"),
        ("tenancy", "0001_initial"),
        ("attendance", "0002_alter_studentattendance_attendance_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAttendanceBulk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_date", models.DateField()),
                (
                    "attendance_type",
                    models.CharField(
                        choices=[
                            ("P", "Present"),
                            ("A", "Absent"),
                            ("L", "Late"),
                            ("F", "Half Day"),
                            ("H", "Holiday"),
                        ],
                        max_length=1,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("class_id", models.PositiveIntegerField(blank=True, null=True)),
                ("section_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "student_record_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_attendance_bulks",
                        to="tenancy.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_bulk_rows",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_attendance_bulk",
                "ordering": ["-attendance_date", "student_id"],
            },
        ),
    ]
