# Generated by Django 6.0.3 on 2026-03-31 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_inventory_models"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("sub_title", models.TextField(blank=True)),
                ("applicable_for", models.JSONField(blank=True, default=list)),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="settings/maintenance/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_setting",
                        to="tenancy.school",
                    ),
                ),
            ],
            options={
                "db_table": "maintenance_settings",
            },
        ),
    ]
