# Generated by Django 6.0.3 on 2026-03-31 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_maintenancesetting"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsGateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gateway_name", models.CharField(max_length=100)),
                ("gateway_type", models.CharField(default="custom", max_length=30)),
                ("active_status", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_gateways",
                        to="tenancy.school",
                    ),
                ),
            ],
            options={
                "db_table": "sms_gateways",
                "ordering": ["gateway_name"],
            },
        ),
        migrations.CreateModel(
            name="CustomSmsSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gateway_name", models.CharField(max_length=100)),
                ("set_auth", models.BooleanField(default=False)),
                ("gateway_url", models.URLField(max_length=500)),
                ("send_to_parameter_name", models.CharField(max_length=100)),
                ("messege_to_parameter_name", models.CharField(max_length=100)),
                (
                    "request_method",
                    models.CharField(
                        choices=[("GET", "GET"), ("POST", "POST")], max_length=10
                    ),
                ),
                ("param_key_1", models.CharField(blank=True, max_length=100)),
                ("param_value_1", models.CharField(blank=True, max_length=255)),
                ("param_key_2", models.CharField(blank=True, max_length=100)),
                ("param_value_2", models.CharField(blank=True, max_length=255)),
                ("param_key_3", models.CharField(blank=True, max_length=100)),
                ("param_value_3", models.CharField(blank=True, max_length=255)),
                ("param_key_4", models.CharField(blank=True, max_length=100)),
                ("param_value_4", models.CharField(blank=True, max_length=255)),
                ("param_key_5", models.CharField(blank=True, max_length=100)),
                ("param_value_5", models.CharField(blank=True, max_length=255)),
                ("param_key_6", models.CharField(blank=True, max_length=100)),
                ("param_value_6", models.CharField(blank=True, max_length=255)),
                ("param_key_7", models.CharField(blank=True, max_length=100)),
                ("param_value_7", models.CharField(blank=True, max_length=255)),
                ("param_key_8", models.CharField(blank=True, max_length=100)),
                ("param_value_8", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_sms_settings",
                        to="tenancy.school",
                    ),
                ),
                (
                    "gateway",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_setting",
                        to="core.smsgateway",
                    ),
                ),
            ],
            options={
                "db_table": "custom_sms_settings",
            },
        ),
        migrations.AddConstraint(
            model_name="smsgateway",
            constraint=models.UniqueConstraint(
                fields=("school", "gateway_name"), name="uq_sms_gateway_school_name"
            ),
        ),
    ]
