# Generated by Django 6.0.3 on 2026-03-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_smsgateway_customsmssetting_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsgateway",
            name="provider_config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
