# Generated by Django 6.0.3 on 2026-04-02 05:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_smsgateway_provider_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customsmssetting",
            name="gateway",
        ),
        migrations.RemoveField(
            model_name="customsmssetting",
            name="school",
        ),
        migrations.RemoveField(
            model_name="maintenancesetting",
            name="school",
        ),
        migrations.RemoveConstraint(
            model_name="smsgateway",
            name="uq_sms_gateway_school_name",
        ),
        migrations.DeleteModel(
            name="CustomSmsSetting",
        ),
        migrations.DeleteModel(
            name="MaintenanceSetting",
        ),
        migrations.DeleteModel(
            name="SmsGateway",
        ),
    ]
