# Generated by Django 4.2.11 on 2026-03-25 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenancy", "0001_initial"),
        ("students", "0004_studentgroup_and_student_student_group"),
        ("core", "0003_classroom"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignedIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("point", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_incidents",
                        to="core.academicyear",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="behaviour_assignments_done",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "behaviour_assigned_incidents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("point", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("active_status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behaviour_incidents",
                        to="tenancy.school",
                    ),
                ),
            ],
            options={
                "db_table": "behaviour_incidents",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="BehaviourRecordSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_comment", models.BooleanField(default=False)),
                ("parent_comment", models.BooleanField(default=False)),
                ("student_view", models.BooleanField(default=False)),
                ("parent_view", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behaviour_setting",
                        to="tenancy.school",
                    ),
                ),
            ],
            options={
                "db_table": "behaviour_record_settings",
            },
        ),
        migrations.CreateModel(
            name="AssignedIncidentComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="behaviour.assignedincident",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_incident_comments",
                        to="tenancy.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="behaviour_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "behaviour_assigned_incident_comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="assignedincident",
            name="incident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="behaviour.incident",
            ),
        ),
        migrations.AddField(
            model_name="assignedincident",
            name="record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_incidents",
                to="students.studentmulticlassrecord",
            ),
        ),
        migrations.AddField(
            model_name="assignedincident",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_incidents",
                to="tenancy.school",
            ),
        ),
        migrations.AddField(
            model_name="assignedincident",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_incidents",
                to="students.student",
            ),
        ),
        migrations.AddConstraint(
            model_name="incident",
            constraint=models.UniqueConstraint(
                fields=("school", "title"), name="uq_behaviour_incident_school_title"
            ),
        ),
        migrations.AddConstraint(
            model_name="assignedincident",
            constraint=models.UniqueConstraint(
                fields=("school", "academic_year", "incident", "student", "record"),
                name="uq_behaviour_assignment_scope",
            ),
        ),
    ]
