# Generated by Django 5.2.8 on 2026-03-18 07:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_classperiod'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('bank_name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=60)),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='tenancy.school')),
            ],
            options={
                'db_table': 'bank_accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=140)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=12)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_accounts', to='tenancy.school')),
            ],
            options={
                'db_table': 'chart_of_accounts',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FundTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('transfer_date', models.DateField()),
                ('reference_no', models.CharField(blank=True, max_length=60)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_transfers_created', to=settings.AUTH_USER_MODEL)),
                ('from_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='finance.bankaccount')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_transfers', to='tenancy.school')),
                ('to_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='finance.bankaccount')),
            ],
            options={
                'db_table': 'fund_transfers',
                'ordering': ['-transfer_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('entry_date', models.DateField()),
                ('reference_no', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='core.academicyear')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='finance.chartofaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='tenancy.school')),
            ],
            options={
                'db_table': 'ledger_entries',
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('school', 'account_number'), name='uq_fin_bank_school_account_no'),
        ),
        migrations.AddConstraint(
            model_name='chartofaccount',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='uq_fin_acc_school_code'),
        ),
        migrations.AddConstraint(
            model_name='chartofaccount',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uq_fin_acc_school_name'),
        ),
        migrations.AddIndex(
            model_name='fundtransfer',
            index=models.Index(fields=['school', 'transfer_date'], name='idx_fin_trf_sch_dt'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['school', 'entry_date'], name='idx_fin_led_sch_dt'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['school', 'account'], name='idx_fin_led_sch_acc'),
        ),
    ]
