# Generated by Django 4.2.11 on 2026-03-21 07:41

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_classperiod"),
        ("exams", "0002_exam_is_result_published_exam_published_at_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="examtype",
            name="uq_exam_type_school_title",
        ),
        migrations.AddField(
            model_name="examtype",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exam_types",
                to="core.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="examtype",
            name="active_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="examtype",
            name="average_mark",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="examtype",
            name="is_average",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="examtype",
            constraint=models.UniqueConstraint(
                fields=("school", "academic_year", "title"),
                name="uq_exam_type_school_year_title",
            ),
        ),
    ]
