# Generated by Django 4.2.11 on 2026-03-21 07:48

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_classperiod"),
        ("exams", "0003_remove_examtype_uq_exam_type_school_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamSetup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_title", models.CharField(max_length=120)),
                (
                    "exam_mark",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_setups",
                        to="core.academicyear",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_setups_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setup_items",
                        to="exams.examtype",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_setups",
                        to="tenancy.school",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_setups",
                        to="core.class",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_setups",
                        to="core.section",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_setups",
                        to="core.subject",
                    ),
                ),
            ],
            options={
                "db_table": "exam_setups",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="examsetup",
            constraint=models.UniqueConstraint(
                fields=(
                    "school",
                    "exam_term",
                    "school_class",
                    "section",
                    "subject",
                    "exam_title",
                ),
                name="uq_exam_setup_scope_title",
            ),
        ),
    ]
