# Generated by Django 4.2.11 on 2026-03-21 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_classperiod"),
        ("exams", "0004_examsetup_examsetup_uq_exam_setup_scope_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamRoutine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("room", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_routines",
                        to="core.academicyear",
                    ),
                ),
                (
                    "exam_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_routines",
                        to="core.classperiod",
                    ),
                ),
                (
                    "exam_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routines",
                        to="exams.examtype",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_routines",
                        to="tenancy.school",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_routines",
                        to="core.class",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_routines",
                        to="core.section",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_routines",
                        to="core.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_routines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "exam_routines",
                "ordering": ["exam_date", "start_time", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="examroutine",
            constraint=models.UniqueConstraint(
                fields=("school", "exam_term", "school_class", "section", "subject"),
                name="uq_exam_routine_scope_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="examroutine",
            constraint=models.UniqueConstraint(
                fields=(
                    "school",
                    "exam_term",
                    "school_class",
                    "section",
                    "exam_date",
                    "exam_period",
                ),
                name="uq_exam_routine_scope_date_period",
            ),
        ),
    ]
