# Generated by Django 4.2.11 on 2026-03-21 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_classperiod"),
        ("students", "0002_studentpromotionhistory"),
        ("tenancy", "0001_initial"),
        ("exams", "0005_examroutine_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_attendances",
                        to="core.academicyear",
                    ),
                ),
                (
                    "exam_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="exams.examtype",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attendances",
                        to="tenancy.school",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attendances",
                        to="core.class",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_attendances",
                        to="core.section",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attendances",
                        to="core.subject",
                    ),
                ),
            ],
            options={
                "db_table": "exam_attendances",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ExamAttendanceChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_record_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "attendance_type",
                    models.CharField(
                        choices=[("P", "Present"), ("A", "Absent")],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="exams.examattendance",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attendance_children",
                        to="core.class",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_attendance_children",
                        to="core.section",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attendance_children",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "exam_attendance_children",
                "ordering": ["student_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="examattendancechild",
            constraint=models.UniqueConstraint(
                fields=("attendance", "student"),
                name="uq_exam_attendance_child_attendance_student",
            ),
        ),
        migrations.AddConstraint(
            model_name="examattendance",
            constraint=models.UniqueConstraint(
                fields=("school", "exam_term", "school_class", "section", "subject"),
                name="uq_exam_attendance_scope",
            ),
        ),
    ]
