# Generated by Django 4.2.11 on 2026-03-21 08:53

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_classperiod"),
        ("students", "0002_studentpromotionhistory"),
        ("exams", "0006_examattendance_examattendancechild_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamMarkRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_record_id", models.BigIntegerField(blank=True, null=True)),
                ("is_absent", models.BooleanField(default=False)),
                (
                    "total_marks",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "total_gpa_point",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=4
                    ),
                ),
                ("total_gpa_grade", models.CharField(blank=True, max_length=10)),
                ("teacher_remarks", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_mark_registers",
                        to="core.academicyear",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_mark_registers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mark_registers",
                        to="exams.examtype",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_mark_registers",
                        to="tenancy.school",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_mark_registers",
                        to="core.class",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_mark_registers",
                        to="core.section",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_mark_registers",
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_mark_registers",
                        to="core.subject",
                    ),
                ),
            ],
            options={
                "db_table": "exam_mark_registers",
                "ordering": ["student_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExamMarkRegisterPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marks",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam_setup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mark_register_parts",
                        to="exams.examsetup",
                    ),
                ),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="exams.exammarkregister",
                    ),
                ),
            ],
            options={
                "db_table": "exam_mark_register_parts",
                "ordering": ["exam_setup_id", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="exammarkregisterpart",
            constraint=models.UniqueConstraint(
                fields=("register", "exam_setup"),
                name="uq_exam_mark_register_part_register_setup",
            ),
        ),
        migrations.AddConstraint(
            model_name="exammarkregister",
            constraint=models.UniqueConstraint(
                fields=(
                    "school",
                    "exam_term",
                    "school_class",
                    "section",
                    "subject",
                    "student",
                ),
                name="uq_exam_mark_register_scope_student",
            ),
        ),
    ]
