# Generated by Django 4.2.11 on 2026-03-21 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_classperiod"),
        ("tenancy", "0001_initial"),
        ("exams", "0007_exammarkregister_exammarkregisterpart_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamResultPublish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_result_publishes",
                        to="core.academicyear",
                    ),
                ),
                (
                    "exam_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_publishes",
                        to="exams.examtype",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_result_publishes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_result_publishes",
                        to="tenancy.school",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_result_publishes",
                        to="core.class",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_result_publishes",
                        to="core.section",
                    ),
                ),
            ],
            options={
                "db_table": "exam_result_publishes",
                "ordering": ["-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="examresultpublish",
            constraint=models.UniqueConstraint(
                fields=("school", "exam_term", "school_class", "section"),
                name="uq_exam_result_publish_scope",
            ),
        ),
    ]
