# Generated by Django 4.2.11 on 2026-03-21 09:14

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_classperiod"),
        ("students", "0002_studentpromotionhistory"),
        ("tenancy", "0001_initial"),
        ("exams", "0008_examresultpublish_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnlineExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("end_date_time", models.DateTimeField()),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                ("instruction", models.TextField(blank=True)),
                ("status", models.PositiveSmallIntegerField(default=0)),
                ("auto_mark", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="online_exams",
                        to="core.academicyear",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_exams",
                        to="tenancy.school",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_exams",
                        to="core.class",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_exams",
                        to="core.section",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_exams",
                        to="core.subject",
                    ),
                ),
            ],
            options={
                "db_table": "online_exams",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="OnlineExamTake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_marks",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                ("status", models.PositiveSmallIntegerField(default=0)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "online_exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="takes",
                        to="exams.onlineexam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_exam_takes",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "online_exam_takes",
                "ordering": ["student_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="onlineexamtake",
            constraint=models.UniqueConstraint(
                fields=("online_exam", "student"),
                name="uq_online_exam_take_exam_student",
            ),
        ),
        migrations.AddConstraint(
            model_name="onlineexam",
            constraint=models.UniqueConstraint(
                fields=("school", "school_class", "section", "subject", "title"),
                name="uq_online_exam_scope_title",
            ),
        ),
    ]
