# Generated by Django 4.2.11 on 2026-03-21 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_classperiod"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenancy", "0001_initial"),
        ("students", "0002_studentpromotionhistory"),
        ("exams", "0009_onlineexam_onlineexamtake_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeatPlanSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.BooleanField(default=True)),
                ("student_photo", models.BooleanField(default=True)),
                ("student_name", models.BooleanField(default=True)),
                ("roll_no", models.BooleanField(default=True)),
                ("admission_no", models.BooleanField(default=True)),
                ("class_section", models.BooleanField(default=True)),
                ("exam_name", models.BooleanField(default=True)),
                ("academic_year_label", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seat_plan_settings",
                        to="core.academicyear",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_plan_settings",
                        to="tenancy.school",
                    ),
                ),
            ],
            options={
                "db_table": "seat_plan_settings",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="SeatPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_record_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seat_plans",
                        to="core.academicyear",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seat_plans_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_plans",
                        to="exams.examtype",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_plans",
                        to="tenancy.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_plans",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "seat_plans",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="AdmitCardSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admit_layout", models.PositiveSmallIntegerField(default=1)),
                ("student_photo", models.BooleanField(default=True)),
                ("student_name", models.BooleanField(default=True)),
                ("admission_no", models.BooleanField(default=True)),
                ("class_section", models.BooleanField(default=True)),
                ("exam_name", models.BooleanField(default=True)),
                ("academic_year_label", models.BooleanField(default=True)),
                ("principal_signature", models.BooleanField(default=False)),
                ("guardian_name", models.BooleanField(default=False)),
                ("class_teacher_signature", models.BooleanField(default=False)),
                ("school_address", models.BooleanField(default=False)),
                ("student_download", models.BooleanField(default=True)),
                ("parent_download", models.BooleanField(default=True)),
                ("student_notification", models.BooleanField(default=False)),
                ("parent_notification", models.BooleanField(default=False)),
                ("admit_sub_title", models.CharField(blank=True, max_length=190)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admit_card_settings",
                        to="core.academicyear",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admit_card_settings",
                        to="tenancy.school",
                    ),
                ),
            ],
            options={
                "db_table": "admit_card_settings",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="AdmitCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_record_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admit_cards",
                        to="core.academicyear",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admit_cards_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admit_cards",
                        to="exams.examtype",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admit_cards",
                        to="tenancy.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admit_cards",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "admit_cards",
                "ordering": ["-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="seatplansetting",
            constraint=models.UniqueConstraint(
                fields=("school", "academic_year"), name="uq_seat_plan_setting_scope"
            ),
        ),
        migrations.AddConstraint(
            model_name="seatplan",
            constraint=models.UniqueConstraint(
                fields=("school", "academic_year", "exam_term", "student"),
                name="uq_seat_plan_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="admitcardsetting",
            constraint=models.UniqueConstraint(
                fields=("school", "academic_year"), name="uq_admit_card_setting_scope"
            ),
        ),
        migrations.AddConstraint(
            model_name="admitcard",
            constraint=models.UniqueConstraint(
                fields=("school", "academic_year", "exam_term", "student"),
                name="uq_admit_card_scope",
            ),
        ),
    ]
