# Generated by Django 5.2.8 on 2026-03-17 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        ('students', '0002_studentpromotionhistory'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassOptionalSubjectSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa_above', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'class_optional_subject_setup',
            },
        ),
        migrations.CreateModel(
            name='OptionalSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'optional_subject_assignments',
            },
        ),
        migrations.AlterModelOptions(
            name='classsubjectassignment',
            options={'ordering': ['school_class_id', 'section_id', 'subject_id']},
        ),
        migrations.RemoveConstraint(
            model_name='classsubjectassignment',
            name='uq_class_section_subject_assignment',
        ),
        migrations.AddField(
            model_name='classroutineslot',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classroutineslot',
            name='class_period_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroutineslot',
            name='day_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroutineslot',
            name='is_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classroutineslot',
            name='room_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classsubjectassignment',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_subject_assignments', to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='classsubjectassignment',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classsubjectassignment',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_subject_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classteacherassignment',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='classsubjectassignment',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'school_class', 'section', 'subject'), name='uq_class_section_subject_assignment'),
        ),
        migrations.AddField(
            model_name='classoptionalsubjectsetup',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_optional_setups', to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='classoptionalsubjectsetup',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_optional_setups', to='tenancy.school'),
        ),
        migrations.AddField(
            model_name='classoptionalsubjectsetup',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_setups', to='core.class'),
        ),
        migrations.AddField(
            model_name='optionalsubjectassignment',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optional_subject_assignments', to='core.academicyear'),
        ),
        migrations.AddField(
            model_name='optionalsubjectassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_subject_assignments', to='students.student'),
        ),
        migrations.AddField(
            model_name='optionalsubjectassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_student_assignments', to='core.subject'),
        ),
        migrations.AddConstraint(
            model_name='classoptionalsubjectsetup',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'school_class'), name='uq_optional_setup_scope'),
        ),
        migrations.AddConstraint(
            model_name='optionalsubjectassignment',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year'), name='uq_optional_subject_student_year'),
        ),
    ]
