# Generated by Django 5.2.8 on 2026-03-17 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_classoptionalsubjectsetup_optionalsubjectassignment_and_more'),
        ('core', '0001_initial'),
        ('students', '0002_studentpromotionhistory'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_date', models.DateField()),
                ('submission_date', models.DateField()),
                ('evaluation_date', models.DateField(blank=True, null=True)),
                ('marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('description', models.TextField()),
                ('file', models.CharField(blank=True, max_length=400)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='core.academicyear')),
                ('class_id_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='core.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_homeworks', to=settings.AUTH_USER_MODEL)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_homeworks', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='tenancy.school')),
                ('section_id_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='core.section')),
                ('subject_id_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='core.subject')),
            ],
            options={
                'db_table': 'homeworks',
                'ordering': ['-homework_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('as', 'Assignment'), ('st', 'Study Material'), ('sy', 'Syllabus'), ('ot', 'Others Download')], max_length=2)),
                ('available_for_admin', models.BooleanField(default=False)),
                ('available_for_all_classes', models.BooleanField(default=False)),
                ('upload_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('upload_file', models.CharField(blank=True, max_length=400)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_contents', to='core.academicyear')),
                ('class_id_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_contents', to='core.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_contents', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_contents', to='tenancy.school')),
                ('section_id_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_contents', to='core.section')),
            ],
            options={
                'db_table': 'uploaded_contents',
                'ordering': ['-upload_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('complete_status', models.CharField(choices=[('C', 'Completed'), ('I', 'Incomplete'), ('P', 'Pending')], default='P', max_length=1)),
                ('note', models.TextField(blank=True)),
                ('file', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_homework_submissions', to=settings.AUTH_USER_MODEL)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academics.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='students.student')),
            ],
            options={
                'db_table': 'homework_submissions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('homework', 'student'), name='uq_homework_student_submission')],
            },
        ),
    ]
