# Generated by Django 5.2.8 on 2026-03-17 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_homework_uploadedcontent_homeworksubmission'),
        ('core', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=255)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='core.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lessons', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='tenancy.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.class')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='core.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.subject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_lessons', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['school_class_id', 'section_id', 'subject_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('sub_topic', models.CharField(blank=True, max_length=255)),
                ('lecture_youube_link', models.TextField(blank=True)),
                ('lecture_vedio', models.TextField(blank=True)),
                ('attachment', models.CharField(blank=True, max_length=400)),
                ('teaching_method', models.TextField(blank=True)),
                ('general_objectives', models.TextField(blank=True)),
                ('previous_knowlege', models.TextField(blank=True)),
                ('comp_question', models.TextField(blank=True)),
                ('zoom_setup', models.TextField(blank=True)),
                ('presentation', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('lesson_date', models.DateField()),
                ('competed_date', models.DateField(blank=True, null=True)),
                ('completed_status', models.CharField(blank=True, max_length=50)),
                ('room_id', models.PositiveIntegerField(blank=True, null=True)),
                ('class_period_id', models.PositiveIntegerField(blank=True, null=True)),
                ('routine_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='core.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lesson_plans', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner_lesson_refs', to='academics.lesson')),
                ('lesson_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='academics.lesson')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='tenancy.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='core.class')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='core.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='core.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_lesson_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lesson_planners',
                'ordering': ['lesson_date', 'routine_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_topics', to='core.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lesson_topics', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_groups', to='academics.lesson')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_topics', to='tenancy.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_topics', to='core.class')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_topics', to='core.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_topics', to='core.subject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_lesson_topics', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_topic_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lesson_topics',
                'ordering': ['school_class_id', 'section_id', 'subject_id', 'lesson_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonTopicDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=255)),
                ('completed_status', models.CharField(blank=True, max_length=50)),
                ('competed_date', models.DateField(blank=True, null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lesson_topic_details', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_details', to='academics.lesson')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='academics.lessontopic')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_lesson_topic_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lesson_topic_details',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LessonPlanTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_topic_title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='academics.lessonplanner')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_topics', to='academics.lessontopicdetail')),
            ],
            options={
                'db_table': 'lesson_plan_topics',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='lessonplanner',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner_topic_refs', to='academics.lessontopicdetail'),
        ),
        migrations.AddField(
            model_name='lessonplanner',
            name='topic_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='academics.lessontopicdetail'),
        ),
        migrations.AddConstraint(
            model_name='lessontopic',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'school_class', 'section', 'subject', 'lesson'), name='uq_lesson_topic_scope'),
        ),
    ]
