from django.urls import path
from .views import (
    AcademicClassPerformanceReportView,
    AccountsExpenseReportView,
    AccountsFeeCollectionReportView,
    BalanceFeesReportView,
    BehaviourIncidentsReportView,
    ClassReportView,
    ClassRoutineReportView,
    CollectionReportView,
    ExamMarksReportView,
    ExamResultSummaryReportView,
    ExamRoutineReportView,
    GuardianReportView,
    HrStaffAttendanceReportView,
    InventoryStockReportView,
    LibraryIssueReturnReportView,
    MarkSheetReportStudentView,
    MeritListReportView,
    OnlineExamReportView,
    PayrollReportView,
    ProgressCardReportView,
    StudentDormitoryReportView,
    StudentFineReportView,
    StudentReportView,
    StudentAttendanceReportView,
    StudentListReportView,
    StudentTransportReportView,
    TabulationSheetReportView,
    TeacherClassRoutineReportView,
    TransportStudentReportView,
    ExamReportView,
    StaffReportView,
    FeesReportView,
    AccountsReportView,
)

app_name = 'reports'

urlpatterns = [
    path("accounts/fee-collection/", AccountsFeeCollectionReportView.as_view(), name="accounts_fee_collection_report"),
    path("accounts/expense/", AccountsExpenseReportView.as_view(), name="accounts_expense_report"),
    path("students/list/", StudentListReportView.as_view(), name="students_list_report"),
    path("students/attendance/", StudentAttendanceReportView.as_view(), name="students_attendance_report"),
    path("examination/marks/", ExamMarksReportView.as_view(), name="examination_marks_report"),
    path("examination/result-summary/", ExamResultSummaryReportView.as_view(), name="examination_result_summary_report"),
    path("library/issue-return/", LibraryIssueReturnReportView.as_view(), name="library_issue_return_report"),
    path("academic/class-performance/", AcademicClassPerformanceReportView.as_view(), name="academic_class_performance_report"),
    path("hr/staff-attendance/", HrStaffAttendanceReportView.as_view(), name="hr_staff_attendance_report"),
    path("transport/student/", TransportStudentReportView.as_view(), name="transport_student_report"),
    path("inventory/stock/", InventoryStockReportView.as_view(), name="inventory_stock_report"),
    path("behaviour/incidents/", BehaviourIncidentsReportView.as_view(), name="behaviour_incidents_report"),
    path("student/", StudentReportView.as_view(), name="student_report"),
    path("exam/", ExamReportView.as_view(), name="exam_report"),
    path("staff/", StaffReportView.as_view(), name="staff_report"),
    path("fees/", FeesReportView.as_view(), name="fees_report"),
    path("accounts/", AccountsReportView.as_view(), name="accounts_report"),

    # PHP-compatible report aliases (from upload1 routes) mapped to modular report views.
    path("students/student-report/", StudentReportView.as_view(), name="students_student_report"),
    path("students/guardian-report/", GuardianReportView.as_view(), name="students_guardian_report"),

    path("fees/balance-fees-report/", BalanceFeesReportView.as_view(), name="fees_balance_fees_report"),
    path("fees/collection-report/", CollectionReportView.as_view(), name="fees_collection_report"),
    path("fees/student-fine-report/", StudentFineReportView.as_view(), name="fees_student_fine_report"),

    path("academics/class-report/", ClassReportView.as_view(), name="academics_class_report"),
    path("academics/class-routine-report/", ClassRoutineReportView.as_view(), name="academics_class_routine_report"),

    path("examination/exam-routine-report/", ExamRoutineReportView.as_view(), name="examination_exam_routine_report"),
    path("examination/teacher-class-routine-report/", TeacherClassRoutineReportView.as_view(), name="examination_teacher_class_routine_report"),
    path("examination/merit-list-report/", MeritListReportView.as_view(), name="examination_merit_list_report"),
    path("examination/online-exam-report/", OnlineExamReportView.as_view(), name="examination_online_exam_report"),
    path("examination/mark-sheet-report-student/", MarkSheetReportStudentView.as_view(), name="examination_mark_sheet_report_student"),
    path("examination/tabulation-sheet-report/", TabulationSheetReportView.as_view(), name="examination_tabulation_sheet_report"),
    path("examination/progress-card-report/", ProgressCardReportView.as_view(), name="examination_progress_card_report"),

    path("accounts/payroll-report/", PayrollReportView.as_view(), name="accounts_payroll_report"),

    path("dormitory/student-dormitory-report/", StudentDormitoryReportView.as_view(), name="dormitory_student_dormitory_report"),
    path("transport/student-transport-report/", StudentTransportReportView.as_view(), name="transport_student_transport_report"),
]
