# Generated by Django 5.2.8 on 2026-03-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("students", "0002_studentpromotionhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentMultiClassRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("roll_no", models.CharField(blank=True, max_length=40)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school_class",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="multi_class_students", to="core.class"),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="multi_class_students",
                        to="core.section",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="multi_class_records", to="students.student"),
                ),
            ],
            options={
                "db_table": "student_multi_class_records",
                "ordering": ["student_id", "-is_default", "school_class_id", "section_id", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="studentmulticlassrecord",
            constraint=models.UniqueConstraint(
                fields=("student", "school_class", "section", "roll_no"),
                name="uq_student_multiclass_unique_record",
            ),
        ),
    ]
