# Generated by Django 5.2.8 on 2026-03-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_studentmulticlassrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="student_groups", to="tenancy.school"),
                ),
            ],
            options={
                "db_table": "student_groups",
                "ordering": ["name"],
            },
        ),
        migrations.AddConstraint(
            model_name="studentgroup",
            constraint=models.UniqueConstraint(fields=("school", "name"), name="uq_student_group_school_name"),
        ),
        migrations.AddField(
            model_name="student",
            name="student_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="students.studentgroup",
            ),
        ),
    ]
