# Generated by Django 5.2.8 on 2026-03-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('status_after', models.CharField(blank=True, choices=[('new', 'New'), ('contacted', 'Contacted'), ('visited', 'Visited'), ('enrolled', 'Enrolled'), ('declined', 'Declined')], help_text='Inquiry status set at the time of this follow-up (optional)', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admission_follow_ups',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('class_name', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('visited', 'Visited'), ('enrolled', 'Enrolled'), ('declined', 'Declined')], default='new', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admission_inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
