# Generated by Django 5.2.8 on 2026-03-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0003_visitorbookentry"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitorbookentry",
            name="file_url",
            field=models.FileField(blank=True, null=True, upload_to="admissions/visitor_book/"),
        ),
        migrations.CreateModel(
            name="ComplaintEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("complaint_by", models.CharField(max_length=255)),
                ("complaint_type", models.CharField(max_length=120)),
                ("complaint_source", models.CharField(max_length=120)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("date", models.DateField(blank=True, null=True)),
                ("action_taken", models.CharField(blank=True, max_length=255)),
                ("assigned", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="admissions/complaints/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaint_entries_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaint_entries",
                        to="tenancy.school",
                    ),
                ),
            ],
            options={
                "db_table": "complaint_entries",
                "ordering": ["-created_at"],
            },
        ),
    ]
