# Generated by Django 5.2.8 on 2026-03-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0004_complaintentry_and_visitor_file"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostalReceiveEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("from_title", models.CharField(max_length=255)),
                ("reference_no", models.CharField(max_length=120)),
                ("address", models.CharField(max_length=255)),
                ("note", models.TextField(blank=True)),
                ("to_title", models.CharField(max_length=255)),
                ("date", models.DateField(blank=True, null=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="admissions/postal_receive/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="postal_receive_entries_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postal_receive_entries",
                        to="tenancy.school",
                    ),
                ),
            ],
            options={
                "db_table": "postal_receive_entries",
                "ordering": ["-created_at"],
            },
        ),
    ]
