# Generated by Django 4.2.11 on 2026-03-24 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_classperiod"),
        ("admissions", "0007_idcardtemplate_certificatetemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="admissionfollowup",
            name="response",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="admissioninquiry",
            name="active_status",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="admissioninquiry",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="admissioninquiry",
            name="assigned",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="admissioninquiry",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_admission_inquiries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="admissioninquiry",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="admissioninquiry",
            name="follow_up_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admissioninquiry",
            name="next_follow_up_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admissioninquiry",
            name="no_of_child",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="admissioninquiry",
            name="query_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="admissioninquiry",
            name="reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admission_reference_inquiries",
                to="admissions.adminsetupentry",
            ),
        ),
        migrations.AddField(
            model_name="admissioninquiry",
            name="school_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admission_inquiries",
                to="core.class",
            ),
        ),
        migrations.AddField(
            model_name="admissioninquiry",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admission_source_inquiries",
                to="admissions.adminsetupentry",
            ),
        ),
        migrations.AlterField(
            model_name="admissioninquiry",
            name="class_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="admissioninquiry",
            name="phone",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
