# Generated by Django 4.2.11 on 2026-03-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0008_admissionfollowup_response_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admissionfollowup",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
