# Generated by Django 5.2.8 on 2026-03-18 06:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_classperiod'),
        ('students', '0002_studentpromotionhistory'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_assignments', to='core.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_assignments', to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_assignments', to='students.student')),
            ],
            options={
                'db_table': 'fees_assignments',
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_groups', to='core.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_groups', to='tenancy.school')),
            ],
            options={
                'db_table': 'fees_groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('online', 'Online'), ('wallet', 'Wallet'), ('cheque', 'Cheque')], default='cash', max_length=10)),
                ('transaction_reference', models.CharField(blank=True, max_length=150)),
                ('note', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees.feesassignment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_payments', to='tenancy.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_payments', to='students.student')),
            ],
            options={
                'db_table': 'fees_payments',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='FeesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_types', to='core.academicyear')),
                ('fees_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_types', to='fees.feesgroup')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_types', to='tenancy.school')),
            ],
            options={
                'db_table': 'fees_types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='feesassignment',
            name='fees_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fees.feestype'),
        ),
        migrations.AddConstraint(
            model_name='feesgroup',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'name'), name='uq_fees_group_school_year_name'),
        ),
        migrations.AddIndex(
            model_name='feespayment',
            index=models.Index(fields=['school', 'student', 'paid_at'], name='idx_fee_pay_sch_stu_dt'),
        ),
        migrations.AddConstraint(
            model_name='feestype',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'fees_group', 'name'), name='uq_fees_type_school_year_group_name'),
        ),
        migrations.AddIndex(
            model_name='feesassignment',
            index=models.Index(fields=['school', 'student', 'status'], name='idx_fee_asg_sch_stu_st'),
        ),
    ]
